Custom test groups feature
owtf/owtf pull request #1154
Opened 2021-07-13 20:49 UTC by EXTREMOPHILARUM

A feature to create custom plugin groups from the front end. The user can select plugins and create groups according to their convenience and execute a custom list of plugins

## Description

### Add groups functionality:
#### Steps:
1. Select plugins & click add group
![add_group](https://user-images.githubusercontent.com/22239978/125520749-da02e6ec-4e92-45d7-9cf1-4cad0936bfa2.png)

2. Enter plugin group name
![entername](https://user-images.githubusercontent.com/22239978/125520969-b8602804-b256-4098-919c-0bf0177371b8.png)

#### Groups added:
![group_added_in_plugin](https://user-images.githubusercontent.com/22239978/125521337-c7d1752e-24ae-48aa-8438-66cb2af20174.png)
![group_added](https://user-images.githubusercontent.com/22239978/125521349-c12a7852-27cb-4186-b096-f4c85862d3d2.png)

### Delete groups functionality:
1. Select plugin group & click Delete group

![delete_group](https://user-images.githubusercontent.com/22239978/125521605-ff3c5a59-834d-48a5-b5f8-33abb8c872e9.png)

## Motivation and Context

The reason for adding this feature is to make it easy for the user to run specific plugins that they run frequently and need to select them repeatedly. This feature aims to reduce this hassle. 

## Reviewers

@viyatb @sharmamohit123 

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Other

### Checklist:

- [ ] My code follows the code style (modified PEP8) of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2021-08-15 17:41 UTC, viyatb requested changes
left some comments. I would add some tests for the backend and frontend changes so that we can be sure that these changes don't break the existing functionality.

2021-08-15 17:41 UTC, viyatb commented on owtf/api/handlers/test_group.py
> +            for plugin_element in plugin_data_list:
this parsing seems weird -- I think urlparsing these parameters into a dictionary or a list would be a cleaner approach.

2021-08-15 17:41 UTC, viyatb commented on owtf/api/handlers/test_group.py
> +            custom_group_name = plugin_dict['group'].split('%3B')[-1]
ditto

2021-08-15 17:41 UTC, viyatb commented on owtf/api/handlers/test_group.py
> +                    groups = plugin_data[1].split('%2C')
ditto

2021-08-15 17:41 UTC, viyatb commented on owtf/managers/plugin.py
> +            plugin_groups_list = Plugin.get_all_plugin_groups(session)
can you write some tests for this? this is a critical piece of code which might break functionality

2021-08-15 17:41 UTC, viyatb commented on owtf/webapp/src/containers/Plugins/api.js
> +            'Content-Type': 'application/x-www-form-urlencoded;charset=UTF-8',
JSON based POST will be simpler than form encoded parameters to parse here imo

2021-08-15 17:41 UTC, viyatb commented on owtf/webapp/src/containers/Plugins/api.js
> +            'Content-Type': 'application/x-www-form-urlencoded;charset=UTF-8',
ditto

2021-08-17 21:17 UTC, EXTREMOPHILARUM commented
Working on them.

2026-06-13 19:02 UTC, viyatb commented
Thanks for the work on this. The branch has been stale for years and no longer applies cleanly, so I am closing the PR. If custom test groups are still a priority, let us pick it up from a fresh issue or PR against current `develop`.

2026-06-13 19:02 UTC, closed without merging