resolves issue #1241
owtf/owtf pull request #1242
Opened 2024-02-28 16:36 UTC by Pratham1812

Hey I have tried fixing #1241 the project now functions  with my python version `3.11.8`.I have resolved the issue of deprecated dependencies. I have also removed one of the dependency `cookies` since it was very outdated, instead i have implemented a one liner approach for the use case of this dependency.

## Description

## Related Issue

## Motivation and Context

The change tries to run owtf on systems with python versions > 3.9

## Reviewers

@viyatb @7a 
## How Has This Been Tested?

## Screenshots (if appropriate):

![image](https://github.com/owtf/owtf/assets/32198580/d2b59928-bb98-4be0-89c6-788b8058d37a)
![image](https://github.com/owtf/owtf/assets/32198580/3fa20ff3-b8ab-4c16-9117-5b0bed2b2d90)

Application running without docker with python versions 3.11.8

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Other

### Checklist:

- [x] My code follows the code style (modified PEP8) of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2024-02-28 17:09 UTC, viyatb requested changes
added some comments

2024-02-28 17:09 UTC, viyatb commented on owtf/transactions/base.py
> -                cookies.append(Cookie.from_string(cookie).to_dict())
can you use `http.cookies` instead of `cookies` package? The reason I prefer to use a std library is that it will handle edge cases better than normal split and get the value.

2024-02-28 17:09 UTC, viyatb commented on owtf/models/user_login_token.py
> -        new_token = cls(user_id=user_id, token=token.decode("ascii"))
I would keep the `.decode` everywhere to handle weird characters - its better to be explicit than implicit :)

2024-03-01 17:24 UTC, Pratham1812 commented
![image](https://github.com/owtf/owtf/assets/32198580/524b9510-9310-4619-9856-1652a055059f)
Hey I tried fixing the issue with worker logs, right now I am not able to find any need for `owtf/files/routes.py`. Could you please check.
@7a @viyatb

2024-03-08 07:21 UTC, viyatb commented on owtf/transactions/base.py
> +                cookies.append([{'name':key,'value':morsel.value} for key,morsel in simpleCookie][0])
did you test this? it seems wrong

```

In [1]: cookie = 'MUID=12345678910111213141516; domain=.bing.com; expires=Sun, 20-Sep-2020 16:55:46 GMT; path=/;, MUIDB=16151413121110987654321; path=/; httponly; expires=Sun, 20-Sep
   ...: -2020 16:55:46 GMT'

In [2]: from http.cookies import SimpleCookie

In [3]: SimpleCookie(cookie)
Out[3]: <SimpleCookie: >

In [4]: SimpleCookie(cookie).__dict__
Out[4]: {}
```

2024-03-08 07:36 UTC, viyatb commented on owtf/transactions/base.py
> +                cookies.append([{'name':key,'value':morsel.value} for key,morsel in simpleCookie][0])
lets replace this with a function from Django source code,

```
def parse_cookie(cookie: str) -> Dict[str, str]:
    """Parse a ``Cookie`` HTTP header into a dict of name/value pairs.

    This function attempts to mimic browser cookie parsing behavior;
    it specifically does not follow any of the cookie-related RFCs
    (because browsers don't either).

    The algorithm used is identical to that used by Django version 1.9.10.

    .. versionadded:: 4.4.2
    """
    cookiedict = {}
    for chunk in cookie.split(str(";")):
        if str("=") in chunk:
            key, val = chunk.split(str("="), 1)
        else:
            # Assume an empty name per
            # https://bugzilla.mozilla.org/show_bug.cgi?id=169091
            key, val = str(""), chunk
        key, val = key.strip(), val.strip()
        if key or val:
            # unquote using Python's algorithm.
            cookiedict[key] = _unquote_cookie(val)
    return cookiedict
```

2024-04-13 23:59 UTC, viyatb requested changes
@Pratham1812 did you test the `SimpleCookie` implementation to see if it works?

2024-04-13 23:59 UTC, viyatb commented on owtf/api/handlers/jwtauth.py
> +from owtf.settings import JWT_SECRET_KEY, JWT_OPTIONS,JWT_ALGORITHM
the spaces are off here

2024-04-14 06:43 UTC, Pratham1812 commented
I have updated the way cookies ae handled also did the other changes. Could you please have a look? @viyatb

2024-05-23 22:26 UTC, viyatb approved these changes

2024-07-10 03:51 UTC, viyatb commented
do you need this if you have the other diff?

2024-08-27 08:36 UTC, closed without merging