Isolates the OWTF webapp from the complete project
owtf/owtf pull request #1277
Opened 2024-06-19 14:22 UTC by Pratham1812

Isolates the OWTF webapp from the complete project
## Description

I have written a new Dockerfile for the sole purpose of deploying the Frontend. A new docker compose file has been written which identifies 3 services now instead of two.

## Related Issue

## Motivation and Context

This is required so as to convert the monolithic architecture of OWTF to one with microservices.
## Reviewers

@viyatb @7a 
## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Other

### Checklist:

- [x] My code follows the code style (modified PEP8) of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2024-06-30 08:50 UTC, viyatb requested changes
most of the changes look good! although I think point of the "production" deployment for OWTF is that you build the frontend once, and serve it through nginx as static files vs npm webpack prod command. you only need the webpack server up and running in the dev mode or just local setup.

2024-06-30 08:50 UTC, viyatb commented on owtf/api/handlers/api_token.py
> +            payload = jwt.decode(token, JWT_SECRET_KEY, options=JWT_OPTIONS,algorithms=[JWT_ALGORITHM])
keep the spacing consistent and the last lines on the files? It might be a setting in your editor :)

2024-06-30 08:50 UTC, viyatb commented on owtf/api/handlers/base.py
> +    CORS_ORIGIN = "http://localhost:8019"
put this in the configuration file instead of hardcoding this here

2024-06-30 08:50 UTC, viyatb commented on owtf/api/handlers/base.py
> +
nit: remove extra line

2024-06-30 10:59 UTC, Pratham1812 commented
Hey I was doing the nginx way before but with that if the user is not running owtf on docker then he will have to setup nginx locally and copy the build files in the appropriate directory. I did the npm approach to avoid this. Should I implement the Nginx way again?

2024-07-10 03:50 UTC, viyatb commented
@Pratham1812 can you rebase so that the Github CI can run the checks?

2024-07-10 06:14 UTC, Pratham1812 commented
@viyatb I have rebased the branch.

2024-08-02 05:28 UTC, viyatb requested changes
alright - I think this is almost there. I want the tests to actually pass - can you look into it?

2024-08-02 05:28 UTC, viyatb commented on .pre-commit-config.yaml
> +        python_version: python3.11
can you leave the newline here?

2024-08-02 05:28 UTC, viyatb commented on docker/Dockerfile.frontend
> +# Start Nginx when the container runs
newline

2024-08-02 05:28 UTC, viyatb commented on owtf/webapp/owtf.conf
> +}
newline

2024-08-02 05:28 UTC, viyatb commented on scripts/setup_webapp.sh
> +# echo $HOME
newline. can you also remove the unneeded commented code?

2024-08-18 02:35 UTC, viyatb commented
@Pratham1812 sorry I merged others' changes and you'll need to pull in the latest and rebase.

2024-08-20 22:12 UTC, merged