[GSoC][Phase-I] Terraform scripts for OWTF Deployment on AWS
owtf/owtf pull request #1282
Opened 2024-07-03 17:33 UTC by rahulsurwade08

I have created terraform scripts to deploy OWTF project on AWS
## Description

I have created terraform and ansible scripts to install and use OWTF project in AWS using docker compose on an EC2 instance
## Related Issue

## Motivation and Context

As part of GSoC 24 deliverable, we have created automation scripts to deploy OWTF project on CSP like AWS
## Reviewers

@7a @viyatb @VinhPham2106 @Pratham1812 
## How Has This Been Tested?

I have used AWS Free tier to test and create required scripts using ansible and terraform to create an EC2 instance and run installation scripts 
## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Other

### Checklist:

- [x] My code follows the code style (modified PEP8) of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2024-07-15 16:24 UTC, VinhPham2106 commented
@rahulsurwade08 I think a README file would be a necessary addition, explaining deployment details and a bit about the purpose

2024-07-16 05:23 UTC, viyatb requested changes
hey @rahulsurwade08, thanks for the PR. There are some changes we need to make before this can be merged. This is too big of a diff to merge in one go - can you separate the Kubernetes changes into a separate PR?

left some comments here, but I'll ask for some more context on Slack.

2024-07-16 05:23 UTC, viyatb commented on infra/terraform/ec2.tf
> +    values = ["ubuntu/images/hvm-ssd/ubuntu-jammy-22.04-amd64-server-*"]
this should be a variable

2024-07-16 05:23 UTC, viyatb commented on infra/terraform/ec2.tf
> +  owners = ["099720109477"] # Canonical
ditto, again this should be variable.

2024-07-16 05:23 UTC, viyatb commented on infra/terraform/ec2.tf
> +  ami = data.aws_ami.ubuntu.id
did you run `tflint` or `terraform fmt` on this? the formatting is off.

2024-07-16 05:23 UTC, viyatb commented on infra/terraform/ec2.tf
> +    volume_size           = "25"
ditto, variable in the variables.tf file

2024-07-16 05:23 UTC, viyatb commented on infra/terraform/ec2.tf
> +  provisioner "local-exec" {
I'd set up AWS SSM instead of relying on SSH. It is much more secure and removes the need to expose port 22 to the internet.

2024-07-16 05:23 UTC, viyatb commented on infra/terraform/output.tf
> +output "owtf_url" {
Assigning and using the raw IP for the Ec2 machine is very insecure - we should have a load balancer in front that proxies request to the EC2 machine which is in a private VPC, so it is never exposed to the internet

2024-07-16 05:23 UTC, viyatb commented on infra/terraform/variable.tf
can you rename this to `variables.tf`?

2024-07-16 05:23 UTC, viyatb commented on infra/terraform/vpc.tf
> +  cidr_block = "10.1.0.0/16"
should be in variables file

2024-07-16 05:23 UTC, viyatb commented on infra/terraform/vpc.tf
> +resource "aws_route" "route" {
what is this for?

2024-07-21 12:11 UTC, closed without merging