OWTF-IG comprehensive update on Enumeration and Discovery
owtf/owtf pull request #1283
Opened 2024-07-09 11:11 UTC by VinhPham2106

Fixed errors of existing tools, added modern tools for enumeration and discovery
## Description

- OWTF container has network capabilities for nmap (and any other tools that needs them)
- SecList has correct name and location in YAML files
- Added "dirsearch" for Active Content Discovery, stop options on 429 to not flood the host and stall the machine
- Added "amass" for additional source of subdomain enumeration 
- Added "nuclei" for quick vulnerability scan (in progress)
- Added "httpx" for quick probing (in progress)
- Added "gau" for passive URL discovery (in progress)
- Redo robots.txt analysis as all links used are deprecated
## Related Issue

## Motivation and Context

Enumeration is more than 50% of the work, so a big focus is put on running dirty and quick tools automatically before digging into further details
## Reviewers

@viyatb @7a 
## How Has This Been Tested?

Docker container is built and all OWTF-IG plugins are run on a chosen host. Confirming the result logged in output files
## Screenshots (if appropriate):

## Types of changes

- [x ] Bug fix (non-breaking change which fixes an issue)
- [x ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Other

### Checklist:

- [x ] My code follows the code style (modified PEP8) of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2024-08-02 03:33 UTC, viyatb commented on docker/Dockerfile
> +RUN setcap cap_net_admin,cap_net_raw=eip $(which nmap)
did you consider the security implications of adding these capabilities? It makes it easier to do privesc :)

2024-08-02 03:34 UTC, viyatb commented on owtf/data/conf/general.yaml
> +    value: echo "@@@PROXYCHAINS_CONFIG@@@" > ./proxychains.conf; @@@TOOL_PROXYCHAINS@@@
newline missing

2024-08-02 03:40 UTC, viyatb requested changes
mostly everything looks good - I'd add a couple comments on how those capabilites change the security assumptions when running or deploying OWTF :)

2024-08-15 19:55 UTC, VinhPham2106 commented
@viyatb I've addressed the security issue by providing user with options, highlighting potential unsafetyness. Please have a look!

2024-08-15 20:50 UTC, viyatb commented
looks good! can you see why the tests are failing?

2024-08-16 03:59 UTC, VinhPham2106 commented
@viyatb fixed it. It was a minor conflict in requirements files!

2024-08-18 02:33 UTC, viyatb approved these changes

2024-08-18 02:33 UTC, merged

2024-08-18 02:33 UTC, viyatb commented
thanks @VinhPham2106!